[build]
  command = "echo 'Using pre-built static site from public directory'"
  publish = "public"
  node_version = "18.16.0"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps --force --no-optional"
  NODE_OPTIONS = "--max-old-space-size=4096"
  GATSBY_TELEMETRY_DISABLED = "1"
  GATSBY_EXPERIMENTAL_LMDB_STORE = "0"
  GATSBY_CACHE_BACKEND = "fs" 